spring:
  application:
    name: eureka-server

  config:
    name: default
  
  profiles:
    active:
    - default
    - dev
    - hml
    - prd
    default: prd

server:
  port: 8761

eureka:
  server:
    renewal-percent-threshold: 0.5
  client:
    register-with-eureka: false
    fetch-registry: false
