spring:
  application:
    name: worker-api

  profiles:
    active:
    - dev
    - hml
    - prd
    default: prd

server:
  error:
    include-stacktrace: never
    include-message: always
    whitelabel:
      enabled: false
