spring:
  config:
    name: dev

  datasource:
    url: jdbc:postgresql://localhost:5440/worker_db
    username: worker_admin
    password: W0RK3R_P4SSW0RD

  jpa:
    properties:
      hibernate:
        format-sql: true
        jdbc:
          dialect: org.hibernate.dialect.PosgtreSQLDialect

  profiles:
    active:
    - dev
    - hlm
    - prd
    default: dev

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: ${PORT:0}
  error:
    include-stacktrace: never
    include-message: always
    whitelabel:
      enabled: false

